spring:
  data:
    cassandra:
      keyspace-name: main
      username: JXhKfAJCZYyjgIrZlHmGdSpl
      password: q6BfU2OtD5QKjy.Tq4O.j8uvFKZIGBp_Qa.rhbnJLrvp5uLRtyrp2u3z9Rfvv011ZCIfw7ie,LJ2A7C15+.Zf48N0oX-Nx5AEZ7+asMkvXgd,SqjJaDXCWnH7XrRyv,v
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
datastax.astra:
    secure-connect-bundle: secure-connect-hawk-blog.zip
astra.db:
    id: 90639f99-4f34-4ef1-bf97-ba162cd3aad9-1
    region: us-east-1
    keyspace: HAWK_BLOG
    application.token: AstraCS:JXhKfAJCZYyjgIrZlHmGdSpl:22e517b8be781c4d22290ae4f46182bdfbd99daab16c544e0a3f4eecb0316fe3

